PF/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PF.Models
{
    public class Categoria
    {
        [Key]
        public int IdCategoria { get; set; }
        [Required]
        [MaxLength(40)]
        public string CategoriaNome { get; set; }
        [MaxLength(256)]
        public string? CategoriaDescricao { get; set; }

        public List<Produto> Produtos { get; set; }
    }
}

PF/Controllers/CategoriaController.cs
namespace PF.Controllers
{
	[Authorize(Roles = nameof(Roles.Admin))]
	public class CategoriaController : Controller
	{
		private readonly ICategoriaRepositorio _categoriaRepo;

		public CategoriaController(ICategoriaRepositorio categoriaRepo)
		{
			_categoriaRepo = categoriaRepo;
		}

		public async Task<IActionResult> Index()
		{
			var categorias = await _categoriaRepo.GetAllCategorias();
			return View(categorias);
		}

		public IActionResult AddCategoria()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddCategoria(CategoriaDataTransferObj categoriaDataTransferObj)
		{
			if (!ModelState.IsValid)
			{
				return View(categoriaDataTransferObj);
			}
			try
			{
				var categoriaAdd = new Categoria
				{
					IdCategoria = categoriaDataTransferObj.IdCategoria,
					CategoriaNome = categoriaDataTransferObj.CategoriaNome
				};
				await _categoriaRepo.AddCategoria(categoriaAdd);
				TempData["successMessage"] = "Categoria adicionada com sucesso";
				return RedirectToAction(nameof(AddCategoria));
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = "Algo deu errado";
				return View(categoriaDataTransferObj);
			}
		}

		public async Task<IActionResult> UpdateCategoria(int id)
		{
			var categoria = await _categoriaRepo.GetCategoriaById(id);
			if (categoria is null)
			{
				throw new InvalidOperationException($"Categoria de id: {id} não pôde ser encontrada");
			};
			var categoriaUp = new CategoriaDataTransferObj
			{
				IdCategoria = categoria.IdCategoria,
				CategoriaNome = categoria.CategoriaNome
			};
			return View(categoriaUp);
		}

		[HttpPost]
		public async Task<IActionResult> UpdateCategoria(CategoriaDataTransferObj categoriaDataTransferObj)
		{
			if (!ModelState.IsValid)
			{
				return View(categoriaDataTransferObj);
			}
			try
			{
				var categoriaAdd = new Categoria
				{
					IdCategoria = categoriaDataTransferObj.IdCategoria,
					CategoriaNome = categoriaDataTransferObj.CategoriaNome
				};
				await _categoriaRepo.UpdateCategoria(categoriaAdd);
				TempData["successMessage"] = "Categoria adicionada com sucesso";
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = "Algo deu errado";
				return View(categoriaDataTransferObj);
			}
		}

		public async Task<IActionResult> DeleteCategoria(int id)
		{
			var categoria = await _categoriaRepo.GetCategoriaById(id);
			if (categoria is null)
			{
				throw new InvalidOperationException($"Categoria de id: {id} não pôde ser encontrada");
			};
			await _categoriaRepo.DeleteCategoria(categoria);
			return RedirectToAction(nameof(Index));
		}
	}
}

PF/Views/Categoria/AddCategoria.cshtml
@model CategoriaDataTransferObj
@{
	ViewData["Title"] = "AddCategoria";
}
<div style="width:50%;">
	<h1>AddCategoria</h1>
	<a asp-action="Index" asp-controller="Categoria" class="btn btn-primary">Voltar</a>
	<form asp-action="AddCategoria">
		<div class="my-2">
			<label>Categoria</label>
			<input type="text" class="form-control" asp-for="CategoriaNome" />
			<span asp-validation-for="CategoriaNome" class="text-danger"></span>
		</div>
		<div class="my-2">
			<button type="submit" class="btn btn-info">Adicionar</button>
		</div>
	</form>
</div>

PF/Views/Categoria/Index.cshtml
@model IEnumerable<Categoria>
@{
}

<h2>Categorias</h2>

<a asp-action="AddCategoria" asp-controller="Categoria" class="btn btn-primary">
	Adicionar Categoria
</a>

<table class="table table-striped my-2">
	<tr>
		<th>Categoria</th>
		<th>Ação</th>
	</tr>

	@foreach (var categoria in Model)
	{
		<tr>
			<td>@categoria.CategoriaNome</td>
			<td>
				<a asp-action="UpdateCategoria" asp-controller="Categoria" asp-route-id="@categoria.IdCategoria" class="btn btn-primary">Editar</a>
				<a asp-action="DeletarCategoria" asp-controller="Categoria" asp-route-id="@categoria.IdCategoria" class="btn btn-danger" onclick="return window.confirm('Você tem certeza?')">Deletar</a>
			</td>
		</tr>
	}
</table>

PF/Views/Categoria/UpdateCategoria.cshtml
@model CategoriaDataTransferObj
@{
	ViewData["Title"] = "UpdateCategoria";
}
<div style="width:50%">
	<h1>UpdateCategoria</h1>
	<a asp-action="Index" asp-controller="Categoria" class="btn btn-primary">Voltar</a>
	<form asp-action="UpdateCategoria">
		<input type="hidden" asp-for="IdCategoria" />
		<div class="my-2">
			<label>Categoria</label>
			<input type="text" class="form-control" asp-for="CategoriaNome" />
			<span asp-validation-for="CategoriaNome" class="text-danger"></span>
		</div>
		<div class="my-2">
			<button type="submit" class="btn btn-info">Atualizar</button>
		</div>
	</form>
</div>