PF/Models/Estoque.cs
using System.ComponentModel.DataAnnotations;

namespace PF.Models
{
	public class Estoque
	{
		[Key]
		public int IdEstoque { get; set; }
		public int ProdutoId { get; set; }
		public int QuantidadeEstoque { get; set; }
		public Produto? Produtos { get; set; }
	}
}

PF/Controllers/EstoqueController.cs
using System.Runtime.InteropServices;

namespace PF.Controllers
{
	[Authorize(Roles = nameof(Roles.Admin))]
	public class EstoqueController : Controller
	{
		private readonly IEstoqueRepositorio _estoqueRepo;
		public EstoqueController(IEstoqueRepositorio estoqueRepo)
		{
			_estoqueRepo = estoqueRepo;
		}
		public async Task<IActionResult> Index(string sTerm = "")
		{
			var estoques = await _estoqueRepo.GetEstoques(sTerm);
			return View(estoques);
		}

		public async Task<IActionResult> ManejarEstoque(int produtoId)
		{
			var estoqueExiste = await _estoqueRepo.GetEstoqueByProdutoId(produtoId);
			var estoque = new EstoqueDataTransferObj
			{
				ProdutoId = produtoId,
				Estoque = estoqueExiste != null ?  estoqueExiste.QuantidadeEstoque : 0 
			};
			return View(estoque);
		}

		[HttpPost]
		public async Task<IActionResult> GerenciarEstoque(EstoqueDataTransferObj estoqueQtd)
		{
		
			if (!ModelState.IsValid)
			{
				return View(estoqueQtd);
			}
			try
			{
				await _estoqueRepo.GerenciarEstoque(estoqueQtd);
				TempData["successMessage"] = "Estoque atualizado com sucesso";
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = "Algo deu errado";
			}

			return RedirectToAction(nameof(Index));
		}
	}
}

PF/Views/Estoque/Index.cshtml
@model IEnumerable<EstoqueDisplayModel>
@{
	ViewData["Title"] = "Index";
}

<h2>Estoques</h2>

<form asp-action="Index" method="get" class="my-2 d-flex gap-2">
	<input type="text" name="sTerm" class="form-control w-25" placeholder="Pesquise por produto" />
	<button type="submit" class="btn btn-primary">Pesquisar</button>
	<a asp-action="Index" asp-controller="Estoque" class="btn btn-danger">Limpar</a>
</form>

<table class="table table-bordered">
	<tr>
		<th>Produto</th>
		<th>Estoque</th>
		<th>Ações</th>
	</tr>
	@foreach (var item in Model)
	{
		<tr>
			<td>@item.ProdutoNome</td>
			<td>@item.Quantidade</td>
			<td>
				<a asp-action="ManejarEstoque" asp-controller="Estoque" asp-route-produtoId="@item.ProdutoId" class="btn btn-info">Atualizar estoque</a>
			</td>
		</tr>
	}
</table>

PF/Views/Estoque/ManejarEstoque.cshtml
@model EstoqueDataTransferObj
@{
    ViewData["Title"] = "ManejarEstoque";
}

<div style="width:50%">
    <h2>Gerenciar Estoque</h2>
    <a asp-action="Index" asp-controller="Estoque" class="btn btn-danger">Voltar</a>
    <form asp-action="GerenciarEstoque">
        <input type="hidden" asp-for="ProdutoId" />
        <div class ="my-2">
            <label>Quantidade</label>
            <input type="number" min="0" value="0" class="form-control" asp-for="Estoque" />
            <span asp-validation-for="Estoque" class="text-danger"></span>
        </div>
        <div class="my-2">
            <button type="submit" class="btn btn-secondary">Atualizar</button>
        </div>
    </form>
</div>