PF/Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing.Printing;

namespace PF.Models
{
	public class Produto
	{
		[Key]
		public int IdProduto { get; set; }
		[Required]
		[MaxLength(40)]
		public string ProdutoNome { get; set; }
		[Required]
		[MaxLength(256)]
		public string ProdutoDescricao { get; set; }
		[Required]
		public double ProdutoPreco { get; set; }
		[Required]
		public int CategoriaId { get; set; }
		public Categoria Categoria { get; set; }

		public string? Imagem { get; set; }

		public List<DetalhePedido> DetalhesPedidos { get; set; }
		public List<DetalheCarrinho> DetalhesCarrinho { get; set; }
		public Estoque Estoques { get; set; }
		[NotMapped]
		public string CategoriaNome { get; set; }
		[NotMapped]
		public int Quantidade { get; set; }
	}
}

PF/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PF.Shared;

namespace PF.Controllers;

[Authorize(Roles = nameof(Roles.Admin))]

public class ProdutoController : Controller
{
	private readonly IProdutoRepositorio _produtoRepo;
	private readonly ICategoriaRepositorio _categoriaRepo;
	private readonly IFileService _fileService;

	public ProdutoController(IProdutoRepositorio produtoRepo, ICategoriaRepositorio categoriaRepo, IFileService fileService)
	{
		_produtoRepo = produtoRepo;
		_categoriaRepo = categoriaRepo;
		_fileService = fileService;
	}

	public async Task<IActionResult> Index()
	{
		var produtos = await _produtoRepo.GetProdutos();
		return View(produtos);
	}

	public async Task<IActionResult> AddProduto()
	{
		var categoriaSelectList = (await _categoriaRepo.GetAllCategorias()).Select(categoria => new SelectListItem
		{
			Text = categoria.CategoriaNome,
			Value = categoria.IdCategoria.ToString()
		});
		ProdutoDataTransferObj produtoAdd = new()
		{
			CategoriaList = categoriaSelectList
		};
		return View(produtoAdd);
	}

	[HttpPost]
	public async Task<IActionResult> AddProduto(ProdutoDataTransferObj produtoAdd)
	{
		var categoriaSelectList = (await _categoriaRepo.GetAllCategorias()).Select(categoria => new SelectListItem
		{
			Text = categoria.CategoriaNome,
			Value = categoria.IdCategoria.ToString()
		});
		produtoAdd.CategoriaList = categoriaSelectList;
		if (!ModelState.IsValid)
		{
			return View(produtoAdd);
		}
		try
		{
			if (produtoAdd.ArquivoImagem != null)
			{
				if (produtoAdd.ArquivoImagem.Length > 1 * 1024 * 1024)
				{
					throw new InvalidOperationException("O tamanho do arquivo não pode exceder 1 MB");
				}
				string[] allowedExtensions = [".jpeg", ".jpg", ".png"];
				string nomeImagem = await _fileService.SalvarArquivo(produtoAdd.ArquivoImagem, allowedExtensions);
				produtoAdd.Imagem = nomeImagem;
			}
			Produto produto = new()
			{
				IdProduto = produtoAdd.ProdutoId,
				ProdutoNome = produtoAdd.ProdutoNome,
				ProdutoDescricao = produtoAdd.ProdutoDescricao,
				Imagem = produtoAdd.Imagem,
				CategoriaId = produtoAdd.CategoriaId,
				ProdutoPreco = produtoAdd.Preco
			};
			await _produtoRepo.AddProduto(produto);
			TempData["successMessage"] = "Produto adiconado com sucesso";
			return RedirectToAction(nameof(Index));
		}
		catch (InvalidOperationException ex)
		{
			TempData["errorMessage"] = ex.Message;
			return View(produtoAdd);
		}
		catch (FileNotFoundException ex)
		{
			TempData["errorMessage"] = ex.Message;
			return View(produtoAdd);
		}
		catch (Exception ex)
		{
			TempData["errorMessage"] = "Produto não pôde ser adicionado";
			return View(produtoAdd);
		}
	}

	public async Task<IActionResult> UpdateProduto(int id)
	{
		var produto = await _produtoRepo.GetProdutoById(id);
		if (produto == null)
		{
			TempData["errorMessage"] = "Produto não encontrado";
			return RedirectToAction(nameof(Index));
		}
		var categoriaSelectList = (await _categoriaRepo.GetAllCategorias()).Select(categoria => new SelectListItem
		{
			Text = categoria.CategoriaNome,
			Value = categoria.IdCategoria.ToString(),
			Selected = categoria.IdCategoria == produto.CategoriaId
		});
		ProdutoDataTransferObj produtoUpdate = new()
		{
			ProdutoId = produto.IdProduto,
			CategoriaList = categoriaSelectList,
			ProdutoNome = produto.ProdutoNome,
			ProdutoDescricao = produto.ProdutoDescricao,
			CategoriaId = produto.CategoriaId,
			Preco = produto.ProdutoPreco,
			Imagem = produto.Imagem
		};
		return View(produtoUpdate);

	}

	[HttpPost]
	public async Task<IActionResult> UpdateProduto(ProdutoDataTransferObj produtoToUpdate)
	{
		var categoriaSelectList = (await _categoriaRepo.GetAllCategorias()).Select(categoria => new SelectListItem
		{
			Value = categoria.IdCategoria.ToString(),
			Text = categoria.CategoriaNome,
			Selected = categoria.IdCategoria == produtoToUpdate.CategoriaId
		});
		produtoToUpdate.CategoriaList = categoriaSelectList;
		if (!ModelState.IsValid)
		{
			return View(produtoToUpdate);
		}
		try
		{
			string imagemAntiga = "";
			if (produtoToUpdate.ArquivoImagem != null)
			{
				if (produtoToUpdate.ArquivoImagem.Length > 1 * 1024 * 1024)
				{
					throw new InvalidOperationException("A imagem não pode exceder 1 MB");
				}
				string[] allowedExtensions = [".jpeg", ".jpg", ".png"];
				string nomeImagem = await _fileService.SalvarArquivo(produtoToUpdate.ArquivoImagem, allowedExtensions);
				imagemAntiga = produtoToUpdate.Imagem;
				produtoToUpdate.Imagem = nomeImagem;
			}

			Produto produto = new()
			{
				IdProduto = produtoToUpdate.ProdutoId,
				ProdutoNome = produtoToUpdate.ProdutoNome,
				ProdutoDescricao = produtoToUpdate.ProdutoDescricao,
				CategoriaId = produtoToUpdate.CategoriaId,
				ProdutoPreco = produtoToUpdate.Preco,
				Imagem = produtoToUpdate.Imagem
			};

			await _produtoRepo.UpdateProduto(produto);
		
			if(!string.IsNullOrEmpty(imagemAntiga))
			{
				_fileService.DeleteArquivo(imagemAntiga);
			}
			TempData["successMessage"] = "Produto atualizado com sucesso";
			return RedirectToAction(nameof(Index));

		}
		catch(InvalidOperationException ex)
		{
			TempData["errorMessage"] = ex.Message;
			return View(produtoToUpdate);
		}
		catch (FileNotFoundException ex)
		{
			TempData["errorMessage"] = ex.Message;
			return View(produtoToUpdate);
		}
		catch (Exception ex)
		{
			TempData["errorMessage"] = "Produto não pôde ser atualizado";
			return View(produtoToUpdate);
		}
	}

    public async Task<IActionResult> DeleteProduto(int id)
    {
        try
        {
            var produto = await _produtoRepo.GetProdutoById(id);
            if (produto == null)
            {
                TempData["errorMessage"] = $"produto with the id: {id} does not found";
            }
            else
            {
                await _produtoRepo.DeleteProduto(produto);
                if (!string.IsNullOrWhiteSpace(produto.Imagem))
                {
                    _fileService.DeleteArquivo(produto.Imagem);
                }
            }
        }
        catch (InvalidOperationException ex)
        {
            TempData["errorMessage"] = ex.Message;
        }
        catch (FileNotFoundException ex)
        {
            TempData["errorMessage"] = ex.Message;
        }
        catch (Exception ex)
        {
            TempData["errorMessage"] = "Error on deleting the data";
        }
        return RedirectToAction(nameof(Index));
    }
}

PF/Views/Produto/AddProduto.cshtml
@model ProdutoDataTransferObj

<div style="width:50%">
    <h2> Add produto </h2>
    <a asp-action="Index" asp-controller="Produto" class="btn btn-primary">Back</a>
    <form asp-action="AddProduto" enctype="multipart/form-data">
        @* <input type="hidden" asp-for="Id" /> *@

        <div class="my-2">
            <label>Produto*</label>
            <input type="text" class="form-control" asp-for="ProdutoNome" />
            <span asp-validation-for="ProdutoNome" class="text-danger"></span>
        </div>
        <div class="my-2">
            <label>Descrição*</label>
            <input type="text" class="form-control" asp-for="ProdutoDescricao" />
            <span asp-validation-for="ProdutoDescricao" class="text-danger"></span>
        </div>

        <div class="my-2">
            <label>genero*</label>
            <select class="form-control" asp-for="CategoriaId" asp-items="Model.CategoriaList">
                <option value="">Select genero</option>
            </select>
            <span asp-validation-for="CategoriaId" class="text-danger"></span>
        </div>

        <div class="my-2">
            <label>Price*</label>
            <input type="number" class="form-control" asp-for="Preco" />
            <span asp-validation-for="Preco" class="text-danger"></span>
        </div>

        <div class="my-2">
            <label>Image</label>
            <input type="file" class="form-control" asp-for="Imagem" />
        </div>

        <div class="my-2">
            <button type="submit" class="btn btn-info">Adicionar</button>
        </div>
    </form>
</div>

PF/Views/Produto/Index.cshtml
@model IEnumerable<Produto>

<h2>Produtos</h2>
<div>
	<a asp-action="AddProduto" asp-controller="Produto" class="btn btn-primary">Adicionar produto</a>

	@if (Model?.Count() > 0)
	{
		<table class="table table-striped my-2">
			<tr>
				<th>Imagem</th>
				<th>Produto</th>
				<th>Categoria</th>
				<th>Preço</th>
				<th>Ações</th>
			</tr>

			@foreach (var produto in Model)
			{
				<tr>
					<td>
						@if (string.IsNullOrWhiteSpace(produto.Imagem))
						{
							<img src="~/images/no_image_available.jpg" style="width:80px;height:100px" alt="Produto" />
						}
						else
						{
							<img src="/images/@produto.Imagem" style="width:80px;height:100px" alt="Produto image" />
						}
					</td>
					<td>@produto.ProdutoNome</td>
					<td>@produto.Categoria.CategoriaNome</td>
					<td>@produto.ProdutoPreco.ToString("C")</td> <!-- Formatação de preço -->
					<td>
						<a asp-action="UpdateProduto" asp-controller="Produto" asp-route-id="@produto.IdProduto" class="btn btn-success">Edit</a>
						<a asp-action="DeleteProduto" asp-controller="Produto" asp-route-id="@produto.IdProduto" class="btn btn-danger" onclick="return window.confirm('Você tem certeza?')">Deletar</a>
					</td>
				</tr>
			}
		</table>
	}
	else
	{
		<h3>Sem produtos</h3>
	}
</div>

PF/Views/Produto/UpdateProduto.cshtml
@model ProdutoDataTransferObj

<div style="width:50%">
    <h2> Update produto </h2>
    <a asp-action="Index" asp-controller="Produto" class="btn btn-primary">Back</a>
    <form asp-action="UpdateProduto" enctype="multipart/form-data">
        <input type="hidden" asp-for="ProdutoId" />
        <input type="hidden" asp-for="Imagem" />

        <div class="my-2">
            <label>produto*</label>
            <input type="text" class="form-control" asp-for="ProdutoNome" />
            <span asp-validation-for="ProdutoNome" class="text-danger"></span>
        </div>

        <div class="my-2">
            <label>produto*</label>
            <input type="text" class="form-control" asp-for="ProdutoDescricao" />
            <span asp-validation-for="ProdutoDescricao" class="text-danger"></span>
        </div>

        <div class="my-2">
            <label>genero*</label>
            <select class="form-control" asp-for="CategoriaId" asp-items="Model.CategoriaList">
                <option value="">Select genero</option>
            </select>
            <span asp-validation-for="CategoriaId" class="text-danger"></span>
        </div>

        <div class="my-2">
            <label>Price*</label>
            <input type="number" class="form-control" asp-for="Preco" />
            <span asp-validation-for="Preco" class="text-danger"></span>
        </div>

        <div class="my-2">
            <label>Image</label>
            @if(!string.IsNullOrEmpty(Model.Imagem))
            {
                <img src="/images/@Model.Imagem" style="width:100px;height:80px"/>
            }
            <input type="file" class="form-control" asp-for="ArquivoImagem" />
        </div>

        <div class="my-2">
            <button type="submit" class="btn btn-info">Update</button>
        </div>
    </form>
</div>